apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mongo
    app: nodeapp
spec:
  selector:
    name: mongo
  ports:
    - name: db
      port: 27017
      targetPort: 27017